---
- name: configure rancher mysql server
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: mysql-rancher.service.j2
      dest: /usr/lib/systemd/system/mysql-rancher.service
    - src: mysql-rancher.env.j2
      dest: /etc/default/mysql-rancher.env
  notify:
    - reload mysql-rancher
    - restart mysql-rancher
  tags:
    - rancher-server
- name: test callback
  sudo: yes
  shell: which lynx
